title: Wilson Rom√£o
logo: https://media.licdn.com/dms/image/v2/D4D03AQEKbYXbiq-ZVg/profile-displayphoto-crop_800_800/B4DZjyE1SzH4AM-/0/1756408011688?e=1771459200&v=beta&t=jjmYEJjQ-E8vY_2lwV0ABdBXQmhwmTgcvmo462U80_Q
#description: teste
#show_downloads: true
theme: jekyll-theme-minimal
